'use client'

import { FormEvent, useState } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'

export function AuthForm({ mode }: { mode: 'login' | 'signup' }) {
  const router = useRouter(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [name, setName] = useState(''); const [error, setError] = useState(''); const [pending, setPending] = useState(false)
  async function submit(event: FormEvent) { event.preventDefault(); setError(''); setPending(true); const supabase = createClient(); const result = mode === 'login' ? await supabase.auth.signInWithPassword({ email, password }) : await supabase.auth.signUp({ email, password, options: { emailRedirectTo: process.env.NEXT_PUBLIC_DEV_SUPABASE_REDIRECT_URL ?? `${window.location.origin}/auth/callback`, data: { full_name: name } } }); setPending(false); if (result.error) { setError(result.error.message.includes('confirm') ? 'Please confirm your email before signing in.' : mode === 'login' ? 'Invalid email or password.' : 'Unable to create your account. Check your details and try again.'); return } router.push(mode === 'login' ? '/' : '/auth/sign-up-success'); router.refresh() }
  return <main className="grid min-h-screen place-items-center bg-background px-6"><div className="w-full max-w-md rounded-2xl border bg-card p-8 shadow-sm"><div className="mb-8"><p className="text-sm font-semibold text-primary">EduEvents</p><h1 className="mt-3 text-3xl font-semibold tracking-tight">{mode === 'login' ? 'Welcome back' : 'Create your account'}</h1><p className="mt-2 text-sm text-muted-foreground">{mode === 'login' ? 'Sign in to manage your college events.' : 'Set up your administrator workspace.'}</p></div><form onSubmit={submit} className="flex flex-col gap-4">{mode === 'signup' && <label className="flex flex-col gap-2 text-sm font-medium">Full name<input required value={name} onChange={(e) => setName(e.target.value)} className="h-11 rounded-lg border bg-background px-3 font-normal outline-none focus:ring-2 focus:ring-primary" /></label>}<label className="flex flex-col gap-2 text-sm font-medium">Email<input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="h-11 rounded-lg border bg-background px-3 font-normal outline-none focus:ring-2 focus:ring-primary" /></label><label className="flex flex-col gap-2 text-sm font-medium">Password<input required minLength={6} type="password" value={password} onChange={(e) => setPassword(e.target.value)} className="h-11 rounded-lg border bg-background px-3 font-normal outline-none focus:ring-2 focus:ring-primary" /></label>{error && <p role="alert" className="text-sm text-destructive">{error}</p>}<button disabled={pending} className="h-11 rounded-lg bg-primary font-medium text-primary-foreground disabled:opacity-60">{pending ? 'Please wait…' : mode === 'login' ? 'Sign in' : 'Create account'}</button></form><p className="mt-6 text-center text-sm text-muted-foreground">{mode === 'login' ? 'Need an account?' : 'Already have an account?'} <Link className="font-medium text-primary hover:underline" href={mode === 'login' ? '/auth/sign-up' : '/auth/login'}>{mode === 'login' ? 'Sign up' : 'Sign in'}</Link></p></div></main>
}
